module.exports = {
  plugins: {
    tailwindcss: {
      content: [
        "./renderer/index.html", 
        "./renderer/src/**/*.{ts,tsx,js,jsx}",
        "./renderer/src/**/*.tsx",
        "./renderer/src/**/*.ts",
        "./renderer/src/**/*.js",
        "./renderer/src/**/*.jsx"
      ],
      darkMode: ["class"],
      theme: {
        container: {
          center: true,
          padding: "2rem",
          screens: {
            "2xl": "1400px",
          },
        },
        extend: {
          colors: {
            border: "oklch(var(--border))",
            input: "oklch(var(--input))",
            ring: "oklch(var(--ring))",
            background: "oklch(var(--background))",
            foreground: "oklch(var(--foreground))",
            primary: { DEFAULT: "oklch(var(--primary))", foreground: "oklch(var(--primary-foreground))" },
            secondary: { DEFAULT: "oklch(var(--secondary))", foreground: "oklch(var(--secondary-foreground))" },
            destructive: { DEFAULT: "oklch(var(--destructive))", foreground: "oklch(var(--destructive-foreground))" },
            muted: { DEFAULT: "oklch(var(--muted))", foreground: "oklch(var(--muted-foreground))" },
            accent: { DEFAULT: "oklch(var(--accent))", foreground: "oklch(var(--accent-foreground))" },
            popover: { DEFAULT: "oklch(var(--popover))", foreground: "oklch(var(--popover-foreground))" },
            card: { DEFAULT: "oklch(var(--card))", foreground: "oklch(var(--card-foreground))" },
            "status-active": "oklch(var(--status-active))",
            "status-completed": "oklch(var(--status-completed))",
            "status-paused": "oklch(var(--status-paused))",
            "status-archived": "oklch(var(--status-archived))",
            "priority-low": "oklch(var(--priority-low))",
            "priority-medium": "oklch(var(--priority-medium))",
            "priority-high": "oklch(var(--priority-high))",
            "priority-critical": "oklch(var(--priority-critical))",
            "category-career": "oklch(var(--category-career))",
            "category-health": "oklch(var(--category-health))",
            "category-learning": "oklch(var(--category-learning))",
            "category-finance": "oklch(var(--category-finance))",
            "category-personal": "oklch(var(--category-personal))",
            "streak-current": "oklch(var(--streak-current))",
            "streak-longest": "oklch(var(--streak-longest))",
            "chart-1": "oklch(var(--chart-1))",
            "chart-2": "oklch(var(--chart-2))",
            "chart-3": "oklch(var(--chart-3))",
            "chart-4": "oklch(var(--chart-4))",
            "chart-5": "oklch(var(--chart-5))",
            sidebar: "oklch(var(--sidebar))",
            "sidebar-foreground": "oklch(var(--sidebar-foreground))",
            "sidebar-primary": "oklch(var(--sidebar-primary))",
            "sidebar-primary-foreground": "oklch(var(--sidebar-primary-foreground))",
            "sidebar-accent": "oklch(var(--sidebar-accent))",
            "sidebar-accent-foreground": "oklch(var(--sidebar-accent-foreground))",
            "sidebar-border": "oklch(var(--sidebar-border))",
            "sidebar-ring": "oklch(var(--sidebar-ring))",
            "sidebar-primary-foreground": "oklch(var(--sidebar-primary-foreground))",
            "sidebar-accent": "oklch(var(--sidebar-accent))",
            "sidebar-accent-foreground": "oklch(var(--sidebar-accent-foreground))",
            "sidebar-border": "oklch(var(--sidebar-border))",
            "sidebar-ring": "oklch(var(--sidebar-ring))",
          },
          borderRadius: {
            lg: "var(--radius)",
            md: "calc(var(--radius) - 2px)",
            sm: "calc(var(--radius) - 4px)",
          },
          keyframes: {
            "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
            "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
            "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
            "slide-in-from-bottom": { from: { transform: "translateY(1rem)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
            "slide-in-from-top": { from: { transform: "translateY(-1rem)", opacity: "0" }, to: { transform: "translateY(0)", opacity: "1" } },
            "slide-in-from-left": { from: { transform: "translateX(-1rem)", opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
            "slide-in-from-right": { from: { transform: "translateX(1rem)", opacity: "0" }, to: { transform: "translateX(0)", opacity: "1" } },
          },
          animation: {
            "accordion-down": "accordion-down 0.2s ease-out",
            "accordion-up": "accordion-up 0.2s ease-out",
            "fade-in": "fade-in 0.2s ease-out",
            "slide-in-from-bottom": "slide-in-from-bottom 0.2s ease-out",
            "slide-in-from-top": "slide-in-from-top 0.2s ease-out",
            "slide-in-from-left": "slide-in-from-left 0.2s ease-out",
            "slide-in-from-right": "slide-in-from-right 0.2s ease-out",
          },
          backdropBlur: { md: "12px" },
          boxShadow: { glass: "0 4px 6px rgba(0,0,0,0.1),0 1px 3px rgba(0,0,0,0.08)", "card-hover": "0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -4px rgba(0,0,0,0.1)" },
        },
        borderColor: (theme) => theme("colors"), // ✅ This generates border-[color] utilities for all colors including 'border'
      },
      plugins: [],
    },
    autoprefixer: {},
  },
};
